export default {
  products: [
    {
      _id: '1',
      name: 'Full Zip Runnig Shirt',
      image: '/images/product-1.jpg',
      price: 60,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countIntock: 6,
    },{
      _id: '2',
      name: 'Full Zip Runnig Shirt',
      image: '/images/product-2.jpg',
      price: 29,
      brand: 'Nike',
      rating: '4.9',
      numReviews: 15,
      countIntock: 0,
    },
    {
      _id: '3',
      name: 'Full Zip Runnig Shirt',
      image: '/images/product-3.jpg',
      price: 33,
      brand: 'Under Armour',
      rating: '4',
      numReviews: 13,
      countIntock: 4,
    },
    {
      _id: '4',
      name: 'Full Zip Runnig Shirt',
      image: '/images/product-4.jpg',
      price: 75,
      brand: 'Adidas',
      rating: '3.5',
      numReviews: 11,
      countIntock: 19,
    },
    {
      _id: '5',
      name: 'Full Zip Runnig Shirt',
      image: '/images/product-5.jpg',
      price: 29,
      brand: 'Nike',
      rating: '3.2',
      numReviews: 15,
      countIntock: 22,
    },
    {
      _id: '6',
      name: 'Full Zip Runnig Shirt',
      image: '/images/product-6.jpg',
      price: 60,
      brand: 'Hiskywin',
      rating: '4.5',
      numReviews: 17,
      countIntock: 12,
    }
  ],
};